name: Quick cargo check

on:
  push:
    branches: [ main, develop ]
    paths:
      - ".github/workflows/quick-check.yml"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/quick-check.yml"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  quick-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo check
        run: cargo check